export const invoiceCategories = [
  "General Maintenance",
  "Plumbing",
  "Electrical Repairs",
  "Security Services",
  "Landscaping & Gardening",
  "Cleaning Services",
  "Pest Control",
  "Painting & Renovations",
  "Waste Management",
  "Water Management",
  "Fire Safety Inspections",
  "Elevator Maintenance",
  "Parking Lot Maintenance",
  "Roofing & Waterproofing",
  "Air Conditioning & HVAC Repairs",
  "Gate & Fence Repairs",
  "Window & Glass Repairs",
  "Lighting Repairs & Upgrades",
  "Swimming Pool Maintenance",
  "Internet & IT Infrastructure",
  "CCTV & Security System Installation",
  "Legal & Compliance Fees",
  "Insurance Premiums",
  "Administrative Services",
  "Audit & Financial Services",
];
